DROP INDEX subindex;

DROP INDEX plaindex;

DROP INDEX desindex;

CREATE INDEX subindex ON IMAGES(SUBJECT)
INDEXTYPE IS CTXSYS.CONTEXT;

CREATE INDEX plaindex ON IMAGES(PLACE)
INDEXTYPE IS CTXSYS.CONTEXT;

CREATE INDEX desindex ON IMAGES(DESCRIPTION)
INDEXTYPE IS CTXSYS.CONTEXT;
